name: 打包vue项目

# 监听push 事件
on: push

# 仓库权限
permissions:
  # 写入权限
  contents: write

# 任务
jobs:
  # 任务1
  npm-build:
    name: npm-build工作
    # 运行环境 运行在github提供的ubuntu最新镜像
    runs-on: ubuntu-latest

    # 步骤
    steps:
    # 步骤名
    - name: 读取仓库内容/代码
      # 借助 actions/checkout@v4 读取代码，复制到ubuntu系统里
      uses: actions/checkout@v4

    - name: 安装依赖 并 打包
      # 执行指令
      run:
        npm install && npm run build

    - name: 部署到github pages
      # 借助 github-pages-deploy-action@v4 部署
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        # 打包后代码存放的分支
        branch: gh-pages
        folder: build